package detector



const {
	NAT_RESTRICT_NONE = 1 	// NAT_FULL_CONE
	NAT_RESTRICT_IP =  2    // NAT_IP_RESTRICT_CONE
	NAT_RESTRICT_PORT = 3	// NAT_PORT_RESTRICT_CONE
	NAT_RESTRICT_UNIQUE = 4	// NAT_SYMMETRIC
}